// 식약처 기준 22종 알레르기 유발 물질
export const ALLERGENS = [
  "eggs",
  "milk",
  "buckwheat",
  "peanut",
  "soybean",
  "wheat",
  "mackerel",
  "crab",
  "shrimp",
  "pork",
  "peach",
  "tomato",
  "sulfite",
  "walnut",
  "chicken",
  "beef",
  "squid",
  "shellfish",
  "pine_nut",
  "oyster",
  "abalone",
  "mussel",
] as const;

export type Allergen = (typeof ALLERGENS)[number];

export const ALLERGEN_LABELS: Record<string, string> = {
  eggs: "난류(가금류)",
  milk: "우유",
  buckwheat: "메밀",
  peanut: "땅콩",
  soybean: "대두",
  wheat: "밀",
  mackerel: "고등어",
  crab: "게",
  shrimp: "새우",
  pork: "돼지고기",
  peach: "복숭아",
  tomato: "토마토",
  sulfite: "아황산류",
  walnut: "호두",
  chicken: "닭고기",
  beef: "쇠고기",
  squid: "오징어",
  shellfish: "조개류(굴,전복,홍합 포함)",
  pine_nut: "잣",
  oyster: "굴",
  abalone: "전복",
  mussel: "홍합",
};
