// Auto-generated by Supabase CLI: npx supabase gen types typescript
// Run the command above after setting up your Supabase project to generate types.
// Below is a manual stub matching our migration schema.

export type Database = {
  public: {
    Tables: {
      franchises: {
        Row: {
          id: string;
          name: string;
          logo_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          logo_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          logo_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "stores_franchise_id_fkey";
            columns: ["id"];
            referencedRelation: "stores";
            referencedColumns: ["franchise_id"];
          },
        ];
      };
      stores: {
        Row: {
          id: string;
          franchise_id: string;
          name: string;
          address: string | null;
          phone: string | null;
          pg_merchant_key: string | null;
          is_active: boolean;
          avg_prep_minutes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          franchise_id: string;
          name: string;
          address?: string | null;
          phone?: string | null;
          pg_merchant_key?: string | null;
          is_active?: boolean;
          avg_prep_minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          franchise_id?: string;
          name?: string;
          address?: string | null;
          phone?: string | null;
          pg_merchant_key?: string | null;
          is_active?: boolean;
          avg_prep_minutes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "stores_franchise_id_fkey";
            columns: ["franchise_id"];
            referencedRelation: "franchises";
            referencedColumns: ["id"];
          },
        ];
      };
      tables: {
        Row: {
          id: string;
          store_id: string;
          table_number: number;
          qr_code_url: string | null;
          current_session_id: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          table_number: number;
          qr_code_url?: string | null;
          current_session_id?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          table_number?: number;
          qr_code_url?: string | null;
          current_session_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tables_store_id_fkey";
            columns: ["store_id"];
            referencedRelation: "stores";
            referencedColumns: ["id"];
          },
        ];
      };
      user_profiles: {
        Row: {
          id: string;
          email: string;
          name: string;
          role: Database["public"]["Enums"]["user_role"];
          franchise_id: string | null;
          store_id: string | null;
          is_approved: boolean;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          name: string;
          role?: Database["public"]["Enums"]["user_role"];
          franchise_id?: string | null;
          store_id?: string | null;
          is_approved?: boolean;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          role?: Database["public"]["Enums"]["user_role"];
          franchise_id?: string | null;
          store_id?: string | null;
          is_approved?: boolean;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          permission: string;
        };
        Insert: {
          id?: string;
          role: Database["public"]["Enums"]["user_role"];
          permission: string;
        };
        Update: {
          id?: string;
          role?: Database["public"]["Enums"]["user_role"];
          permission?: string;
        };
        Relationships: [];
      };
      user_permissions: {
        Row: {
          id: string;
          user_id: string;
          permission: string;
          granted: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          permission: string;
          granted?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          permission?: string;
          granted?: boolean;
        };
        Relationships: [];
      };
      menu_categories: {
        Row: {
          id: string;
          franchise_id: string;
          name: string;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          franchise_id: string;
          name: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          franchise_id?: string;
          name?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "menu_categories_franchise_id_fkey";
            columns: ["franchise_id"];
            referencedRelation: "franchises";
            referencedColumns: ["id"];
          },
        ];
      };
      master_menus: {
        Row: {
          id: string;
          franchise_id: string;
          category_id: string;
          name: string;
          description: string | null;
          price: number;
          image_url: string | null;
          is_active: boolean;
          sort_order: number;
          allergens: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          franchise_id: string;
          category_id: string;
          name: string;
          description?: string | null;
          price: number;
          image_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          allergens?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          franchise_id?: string;
          category_id?: string;
          name?: string;
          description?: string | null;
          price?: number;
          image_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          allergens?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "master_menus_franchise_id_fkey";
            columns: ["franchise_id"];
            referencedRelation: "franchises";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "master_menus_category_id_fkey";
            columns: ["category_id"];
            referencedRelation: "menu_categories";
            referencedColumns: ["id"];
          },
        ];
      };
      orders: {
        Row: {
          id: string;
          store_id: string;
          table_number: number;
          status: string;
          total_amount: number;
          coupon_id: string | null;
          discount_amount: number;
          cancel_reason: string | null;
          memo: string | null;
          session_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          table_number: number;
          status?: string;
          total_amount: number;
          coupon_id?: string | null;
          discount_amount?: number;
          cancel_reason?: string | null;
          memo?: string | null;
          session_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          table_number?: number;
          status?: string;
          total_amount?: number;
          coupon_id?: string | null;
          discount_amount?: number;
          cancel_reason?: string | null;
          memo?: string | null;
          session_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "orders_store_id_fkey";
            columns: ["store_id"];
            referencedRelation: "stores";
            referencedColumns: ["id"];
          },
        ];
      };
      coupons: {
        Row: {
          id: string;
          franchise_id: string;
          store_id: string | null;
          code: string;
          name: string;
          description: string | null;
          discount_type: string;
          discount_value: number;
          min_order_amount: number;
          max_uses: number | null;
          current_uses: number;
          starts_at: string;
          expires_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          franchise_id: string;
          store_id?: string | null;
          code: string;
          name: string;
          description?: string | null;
          discount_type: string;
          discount_value: number;
          min_order_amount?: number;
          max_uses?: number | null;
          current_uses?: number;
          starts_at?: string;
          expires_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          franchise_id?: string;
          store_id?: string | null;
          code?: string;
          name?: string;
          description?: string | null;
          discount_type?: string;
          discount_value?: number;
          min_order_amount?: number;
          max_uses?: number | null;
          current_uses?: number;
          starts_at?: string;
          expires_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "coupons_franchise_id_fkey";
            columns: ["franchise_id"];
            referencedRelation: "franchises";
            referencedColumns: ["id"];
          },
        ];
      };
      coupon_usages: {
        Row: {
          id: string;
          coupon_id: string;
          order_id: string;
          store_id: string;
          discount_amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          coupon_id: string;
          order_id: string;
          store_id: string;
          discount_amount: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          coupon_id?: string;
          order_id?: string;
          store_id?: string;
          discount_amount?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "coupon_usages_coupon_id_fkey";
            columns: ["coupon_id"];
            referencedRelation: "coupons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "coupon_usages_order_id_fkey";
            columns: ["order_id"];
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
      event_banners: {
        Row: {
          id: string;
          franchise_id: string;
          store_id: string | null;
          title: string;
          description: string | null;
          image_url: string | null;
          link_type: string | null;
          link_value: string | null;
          sort_order: number;
          starts_at: string;
          ends_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          franchise_id: string;
          store_id?: string | null;
          title: string;
          description?: string | null;
          image_url?: string | null;
          link_type?: string | null;
          link_value?: string | null;
          sort_order?: number;
          starts_at?: string;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          franchise_id?: string;
          store_id?: string | null;
          title?: string;
          description?: string | null;
          image_url?: string | null;
          link_type?: string | null;
          link_value?: string | null;
          sort_order?: number;
          starts_at?: string;
          ends_at?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "event_banners_franchise_id_fkey";
            columns: ["franchise_id"];
            referencedRelation: "franchises";
            referencedColumns: ["id"];
          },
        ];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          menu_type: string;
          menu_id: string;
          menu_name: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          menu_type?: string;
          menu_id: string;
          menu_name: string;
          quantity?: number;
          unit_price: number;
          total_price: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          menu_type?: string;
          menu_id?: string;
          menu_name?: string;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey";
            columns: ["order_id"];
            referencedRelation: "orders";
            referencedColumns: ["id"];
          },
        ];
      };
      local_menus: {
        Row: {
          id: string;
          store_id: string;
          category_id: string;
          name: string;
          description: string | null;
          price: number;
          image_url: string | null;
          is_active: boolean;
          sort_order: number;
          allergens: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          category_id: string;
          name: string;
          description?: string | null;
          price: number;
          image_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          allergens?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          category_id?: string;
          name?: string;
          description?: string | null;
          price?: number;
          image_url?: string | null;
          is_active?: boolean;
          sort_order?: number;
          allergens?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "local_menus_store_id_fkey";
            columns: ["store_id"];
            referencedRelation: "stores";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "local_menus_category_id_fkey";
            columns: ["category_id"];
            referencedRelation: "menu_categories";
            referencedColumns: ["id"];
          },
        ];
      };
      menu_option_groups: {
        Row: {
          id: string;
          franchise_id: string;
          name: string;
          is_required: boolean;
          min_select: number;
          max_select: number;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          franchise_id: string;
          name: string;
          is_required?: boolean;
          min_select?: number;
          max_select?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          franchise_id?: string;
          name?: string;
          is_required?: boolean;
          min_select?: number;
          max_select?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "menu_option_groups_franchise_id_fkey";
            columns: ["franchise_id"];
            referencedRelation: "franchises";
            referencedColumns: ["id"];
          },
        ];
      };
      menu_option_items: {
        Row: {
          id: string;
          option_group_id: string;
          name: string;
          price_delta: number;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          option_group_id: string;
          name: string;
          price_delta?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          option_group_id?: string;
          name?: string;
          price_delta?: number;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "menu_option_items_option_group_id_fkey";
            columns: ["option_group_id"];
            referencedRelation: "menu_option_groups";
            referencedColumns: ["id"];
          },
        ];
      };
      menu_option_group_links: {
        Row: {
          id: string;
          menu_type: string;
          menu_id: string;
          option_group_id: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          menu_type: string;
          menu_id: string;
          option_group_id: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          menu_type?: string;
          menu_id?: string;
          option_group_id?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: "menu_option_group_links_option_group_id_fkey";
            columns: ["option_group_id"];
            referencedRelation: "menu_option_groups";
            referencedColumns: ["id"];
          },
        ];
      };
      order_item_options: {
        Row: {
          id: string;
          order_item_id: string;
          option_group_name: string;
          option_item_name: string;
          price_delta: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_item_id: string;
          option_group_name: string;
          option_item_name: string;
          price_delta?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_item_id?: string;
          option_group_name?: string;
          option_item_name?: string;
          price_delta?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "order_item_options_order_item_id_fkey";
            columns: ["order_item_id"];
            referencedRelation: "order_items";
            referencedColumns: ["id"];
          },
        ];
      };
      staff_calls: {
        Row: {
          id: string;
          store_id: string;
          table_number: number;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          table_number: number;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          table_number?: number;
          status?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "staff_calls_store_id_fkey";
            columns: ["store_id"];
            referencedRelation: "stores";
            referencedColumns: ["id"];
          },
        ];
      };
      store_menu_overrides: {
        Row: {
          id: string;
          store_id: string;
          master_menu_id: string;
          is_sold_out: boolean;
          is_hidden: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          master_menu_id: string;
          is_sold_out?: boolean;
          is_hidden?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          master_menu_id?: string;
          is_sold_out?: boolean;
          is_hidden?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "store_menu_overrides_store_id_fkey";
            columns: ["store_id"];
            referencedRelation: "stores";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "store_menu_overrides_master_menu_id_fkey";
            columns: ["master_menu_id"];
            referencedRelation: "master_menus";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "pending" | "system_admin" | "brand_admin" | "store_admin";
    };
  };
};
